version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Pa55w0rd_pdm}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "6432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
